name: mm-kiesjekraam
tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

labels:
  app: mm-kiesjekraam

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  tag: latest

network:
  allow-ingress:
    selector: app == 'mm-kiesjekraam'
    ingress:
      - action: Allow
    egress:
      - action: Allow

serviceAccount: app
serviceAccounts:
  app: {}

secrets:
  certificate:
    type: keyvault
    tls: markten
  vault:
    type: keyvault
    secrets:
      REDIS_PASSWORD: redis-primary-key


deployments:
  mm-kiesjekraam:
    image:
      repository: salmagundi/mm-kiesjekraam
    selectorLabels:
      component: kiesjekraam
    containers:
      - name: main
        ports:
          - port: 8080
            name: http
        secrets:
          - vault
        volumes:
          - name: cache
            mountPath: /node_modules/.cache/@babel/register
    volumes:
      - name: cache
        spec:
          emptyDir: {}

services:
  mm-kiesjekraam:
    selector:
      component: kiesjekraam
    ports:
      - port: 8080
        targetPort: 8080

ingress:
  mm-kiesjekraam-internal:
    className: nginx-internal
    paths:
      - path: /
        pathType: Prefix
        service: mm-kiesjekraam
        port: 8080
    tls: certificate

jobs:
  certificate-init:
    image:
      repository: salmagundi/mm-kiesjekraam
    annotations:
      helm.sh/hook: post-install,post-upgrade
    labels:
      component: certificate
    secrets:
      - certificate
    containers:
      - name: main
        command:
          - sleep
        args:
          - "1"
