workloadIdentity: 82370263-90e0-4b27-9d8d-3f8d1689065a
nodepool: cccmrktont01
keyVaultName: markten-o-l5ct7bz3yelys


host: kiesjekraam.makkelijkemarkt.mrkt-o.azure.amsterdam.nl

secrets:
  certificate:
    keyVaultName: shared-o-jpc4hlk5yveei
  vault:
    type: keyvault
    secrets:
      - IAM_CLIENT_ID: iam-client-id
      - IAM_CLIENT_SECRET: iam-client-secret
      - IAM_REALM: iam-realm
      - IAM_ADMIN_USER: iam-admin-user
      - IAM_ADMIN_PASS: iam-admin-pass
      - IAM_URL: iam-url

deployments:
  mm-kiesjekraam:
    env:
      APP_ENV: dev
      APP_DEBUG: true
      ENABLE_CONCEPT_INDELING: true
      REDIS_HOST: markten.redis.cache.windows.net
      REDIS_PORT: 6380
      MAILER_URL: smtp://null:null@salmagundi_mailhog:1025
      MAILER_FROM: noreply@amsterdam.nl
      DEBUG_MODE: false  # for mailing
      INDELING_DAG_OFFSET: 0
      IAM_URL: http://keycloak/auth
      API_KEY: insecure
      API_MMAPPKEY: insecure
      API_URL: http://mm-api-nginx-mm-api:80/api/1.1.0/
      API_READONLY_USER: kjk-non-personal
      API_READONLY_PASS: insecure
      APP_SECRET: insecure
      NODE_ENV: development
      DISABLE_MM_API_DISPATCH_PROTECTION: 1
    secrets:
      - IAM_CLIENT_ID
      - IAM_REAM
      - IAM_CLIENT_SECRET
      - IAM_URL
      - IAM_ADMIN_USER
      - IAM_ADMIN_PASS
    autoscale:
      cpu: 70
      memory: 90
      min: 1
      max: 1

