image:
  registry: 127.0.0.1:5001
  imagePullPolicy: Always

host: kjk.mm

securityContext:
  container:
    readOnlyRootFilesystem: false

secrets:
  certificate:
    enabled: false
  vault:
    enabled: false

deployments:
  mm-kiesjekraam:
    image:
      repository: salmagundi/mm-kiesjekraam
    selectorLabels:
      component: kiesjekraam
    env:
      APP_ENV: dev
      APP_DEBUG: true
      ENABLE_CONCEPT_INDELING: true
      REDIS_HOST: redis-master
      REDIS_PORT: 6379
      REDIS_PASSWORD: insecure
      MAILER_URL: smtp://null:null@salmagundi_mailhog:1025
      MAILER_FROM: noreply@amsterdam.nl
      DEBUG_MODE: false  # for mailing
      INDELING_DAG_OFFSET: 0
      IAM_CLIENT_ID: kiesjekraam
      IAM_CLIENT_SECRET: insecure
      IAM_REALM: kiesjekraam
      IAM_ADMIN_USER: realm_admin
      IAM_ADMIN_PASS: insecure
      IAM_URL: http://keycloak.local/
      API_KEY: insecure
      API_MMAPPKEY: insecure
      API_URL: http://mm-api-nginx-mm-api:80/api/1.1.0/
      API_READONLY_USER: kjk-non-personal
      API_READONLY_PASS: insecure
      APP_SECRET: insecure
      NODE_ENV: development
      DISABLE_MM_API_DISPATCH_PROTECTION: 1
    containers:
      - name: main
        ports:
          - port: 8080
            name: http
        secrets: []

services:
  mm-kiesjekraam:
    selector:
      component: kiesjekraam
    ports:
      - port: 8080
        targetPort: http

ingress:
  mm-kiesjekraam-internal:
    className: nginx
    paths:
      - path: /
        pathType: Prefix
        service: mm-kiesjekraam
        port: 8080

jobs:
  certificate-init:
    enabled: false