workloadIdentity: 7fb05b70-0c2a-4d8c-823d-18e3cd9de9f7
keyVaultName: markten-t-43vb6bx3n4rgq
nodepool: cccmrkttst01

host: kiesjekraam.makkelijkemarkt.mrkt-t.azure.amsterdam.nl

secrets:
  certificate:
    keyVaultName: shared-t-te3lhrptbiube

deployments:
  mm-kiesjekraam:
    env:
      APP_ENV: dev
      APP_DEBUG: true
      ENABLE_CONCEPT_INDELING: true
      REDIS_HOST: markten-t-43vb6bx3n4rgq.redis.cache.windows.net
      REDIS_PORT: 6380
      MAILER_URL: smtp://null:null@salmagundi_mailhog:1025
      MAILER_FROM: noreply@amsterdam.nl
      DEBUG_MODE: false  # for mailing
      INDELING_DAG_OFFSET: 0
      API_MMAPPKEY: insecure
      API_READONLY_USER: kjk-non-personal
      API_READONLY_PASS: insecure
      APP_SECRET: insecure
      NODE_ENV: development
      DISABLE_MM_API_DISPATCH_PROTECTION: 1
    autos cale:
      cpu: 70
      memory: 90
      min: 1
      max: 1